### ISSUE TITLE
error trying to create server

### ISSUE THREAD

**Issue by pr0xr** [packethost/docker-machine-driver-packet#1]
using 0.6.0:
mbp ~ → machine -D  create -d packet --packet-api-key=apikey --packet-project-id=test packet

When trying to create a server I'm getting this error:

```
(packet) Provisioning Packet server...
Error creating machine: Error in driver during machine creation: POST https://api.packet.net/projects/test/devices: 404 Not found
open : no such file or directory
notifying bugsnag: [Error creating machine: Error in driver during machine creation: POST https://api.packet.net/projects/test/devices: 404 Not found]
```

**Comment by crunchywelch** [comment]
HI @pandrew your --packet-project-id must be the ID of the project, not the name of the project. The ID can be pulled down from listing projects directly from the api using your api key, or you can get it from the url on the client portal. For example, while on the device listing page for a project, in the url:

https://app.packet.net/portal#/project/THIS_IS_WHERE_THE_PROJECT_ID_IS/servers

so, your command should look something like this:

`machine -D create -d packet --packet-api-key=apikey --packet-project-id=ABABABABABA-CDCD-EFEF-1212-XXXXXXXXXXX`

Let me know if that doesn't work!

**Comment by pr0xr** [comment]
I don't doubt it would work but it would be easier if the project id could contain the name of the project instead of finding the id by myself. I could not find any documentation on this either. Hopefully this is something that could be resolved in a later version. Thank you for explaining.
