### ISSUE TITLE
add a --packet-sos option

### ISSUE THREAD

**Issue by SvenDowideit** [packethost/docker-machine-driver-packet#10]
to connect to that host's sos console.

**Comment by crunchywelch** [comment]
interesting idea, what command do you see this option associated with? docker-machine ssh ? not sure I understand what the implementation would look like from the ui standpoint, although actually connecting to sos shouldn't be that hard.

**Comment by SvenDowideit** [comment]
yup - `docker-machine ssh --packet-sos myhost`

**Comment by crunchywelch** [comment]
got it, awesome, I don't think this is a big lift. will dig in on it tomorrow and see if we can get it into a release to close out the week :)

**Comment by crunchywelch** [comment]
seems like there isn't a way for the driver to interact with the ssh command, so this would probably require some modifications to machine itself, which isn't outside the realm of possibility, but definitely makes it a bigger project. @SvenDowideit did you have a way in mind to do this just within the driver somehow?

**Comment by crunchywelch** [comment]
@SvenDowideit seems nathan confirms there isn't a way to do this currently with machine, but I'd be down to add something to make it work with jig if you are going to fork over there, lmk what you think.

**Comment by SvenDowideit** [comment]
ah, now there's something we need to think about in jig, yup.

**Comment by displague** [comment]
I believe this is possible today using:

```bash
ssh $(docker-machine inspect \
  --format='{{.Driver.DeviceID}}@sos.{{.Driver.Facility}}.platformequinix.com' \
  $MACHINE
)
```

I'm going to close this issue because it is very stale. Please reopen if this is still of interest.

Let me know if this approach fits your use-case.
