### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by alexellis** [packethost/docker-machine-driver-packet#11]
* `getOsFlavors` might need to be filtered by instance type / and/or restricted to exclude Type2A etc.

* For this line it may be better to put 16.04 as it is your most recent LTS:

https://github.com/packethost/docker-machine-driver-packet/blob/master/driver.go#L67

* README.md is too sparse - should document how to build / get the plugin working.
 * Maybe add a note on the provisioning time ( around 10 min? )
 * Is there a contribution policy or guide?

It would also be great to find a way to have this plugin listed on the official Docker docs page. Under "Machine drivers" here -> https://docs.docker.com/machine/drivers/digital-ocean/

**Comment by jasmingacic** [comment]
This has been fixed by #12
