### ISSUE TITLE
Does not work with docker-machine 0.6.0

### ISSUE THREAD

**Issue by themattrix** [packethost/docker-machine-driver-packet#2]
```
docker-machine version 0.6.0, build e27fb87
```

```
Running pre-create checks...
Creating machine...
(test) Creating SSH key...
Error creating machine: Error in driver during machine creation: unexpected EOF
```

I think you just need to build against the latest libmachine according to this: https://github.com/docker/machine/issues/2706

**Comment by betawaffle** [comment]
Thanks @themattrix! I'll get this fixed today.

**Comment by themattrix** [comment]
Fantastic! :+1:

**Comment by themattrix** [comment]
The new release works perfectly! Thanks, @betawaffle!

**Comment by betawaffle** [comment]
@themattrix Seriously? I found a bug with it :P

**Comment by themattrix** [comment]
Worked for me! I spun up a machine, ran some containers on it and destroyed it all with no issues.

**Comment by betawaffle** [comment]
Great! I'll still re-release it to fix the bug I found.

**Comment by themattrix** [comment]
:+1:

What was the bug?

**Comment by betawaffle** [comment]
If the machine gets created in docker-machine's data store (whatever that is), but the creation fails on the packet side, you can't delete the machine, because it treats 404s as failures.

**Comment by betawaffle** [comment]
@themattrix :tada:

**Comment by themattrix** [comment]
The new release also works well! Thanks again!
