### ISSUE TITLE
Facilities, OS, and Plans should be fetched via API, not hardcoded

### ISSUE THREAD

**Issue by aeryncaen** [packethost/docker-machine-driver-packet#20]
At the moment, this driver requires entirely too much handholding to keep up with Packet's continuous improvements. They provide an API for fetching the information currently hardcoded into the driver, so why aren't we using it?

**Comment by jacobsmith928** [comment]
completely agree.  @crunchywelch @mmlb looping you in.

**Comment by mmlb** [comment]
Yeah there's no reason for not doing it that way, I think so far it's just been easier to add a facility vs reworking the code to be dynamic. PR welcome!

**Comment by jasmingacic** [comment]
Fixed, closing it.
