### ISSUE TITLE
Error creating machine: Error in driver during machine creation: json: Unmarshal(non-pointer string)

### ISSUE THREAD

**Issue by dhrp** [packethost/docker-machine-driver-packet#22]
When using the packet docker-machine driver with the 0.1.5 release consistently fails with the error:

`Error creating machine: Error in driver during machine creation: json: Unmarshal(non-pointer string)`

I was running docker-machine 0.13.0 and it showed the same behavior on 0.14.0.

go-getting the source of the packet driver and installing it with make build && make install solved the issue. 

go version go1.9.2 darwin/amd64
Mac OS X 10.13.3 (High Sierra)

**Comment by aiwantaozi** [comment]
I get the same error on ubuntu 16.04, any update for this issue?

**Comment by fouts-bnet** [comment]
@dhrp @aiwantaozi --

Same result -- same error, but using Rancher Server Preview 4.
I built the driver myself and no longer receive the error.

@mmlb it might be worth rebuilding the release ?

**Comment by mmlb** [comment]
I'll give it a shot (and properly handle deps with dep most likely), will have to wait until tomorrow though.

**Comment by agustinhenze** [comment]
Adding my experience here, the issue is reproducible with the latest release. But if you build master it works perfectly.

**Comment by springerkc** [comment]
It seems that the July update to master has fixed this issue. Can anyone confirm this? please and thank you!

**Comment by alibazlamit** [comment]
@springerkc I can confirm that the issue has been fixed as we have addressed it alongside other issues as well.

Glad its working out well for you!
