### ISSUE TITLE
Error with go get

### ISSUE THREAD

**Issue by insuusvenerati** [packethost/docker-machine-driver-packet#25]
driver.go will not compile because `too many arguments in call to packngo.NewClient
	have (string, string, nil)
	want ()`

Issue occurs with a new installation of go version go1.10.2 linux/amd64

**Comment by t0mk** [comment]
Hey, this is my fault, I changed the args for the `NewClient` in order to be more simple. There is now `NewClientWithAuth` which has the same signature as the old `NewClient`. I will try to produce a PR to fix this.

**Comment by insuusvenerati** [comment]
Appreciated. One day I'll finish learning go and be useful
