### ISSUE TITLE
LICENSE file missing from source code releases

### ISSUE THREAD

**Issue by pmatos** [packethost/docker-machine-driver-packet#27]
It would be useful to package the LICENSE file with the source code releases.

**Comment by jjardon** [comment]
This seems to be done in commit b58889d3d0cf1dbfd44c5da1cc41df5bc340ccf8

**Comment by mmlb** [comment]
Was taken care of a while ago in b58889d3d0cf1dbfd44c5da1cc41df5bc340ccf8, forgot to close this.
