### ISSUE TITLE
Other os than ubuntu_14_04?

### ISSUE THREAD

**Issue by StefanScherer** [packethost/docker-machine-driver-packet#3]
I just tried to spin up an Ubuntu 16.04 machine with your docker-machine driver with

```
docker-machine create -d packet --packet-api-key $(pass packet_token) --packet-os ubuntu_16_04 --packet-plan baremetal_0 --packet-project-id xxx yyy
```

but it complains that only ubuntu_14_04 is allowed. In the web interface there is an Ubuntu 16.04. How can I use that with docker-machine?

**Comment by nathangoulding** [comment]
@StefanScherer You can provision Ubuntu 16.04 using the `ubuntu_16_04_image` operating system slug. (Soon we will support the `ubuntu_16_04` slug without the `_image` suffix, but this won't be live for another week or so.)

**Comment by crunchywelch** [comment]
this is actually a docker machine issue, we can move over to that repo if we want

**Comment by StefanScherer** [comment]
Thanks @nathangoulding !
