### ISSUE TITLE
Unable to Authenticate to Packet Project using project ID & Packet API key

### ISSUE THREAD

**Issue by evectis** [packethost/docker-machine-driver-packet#30]
I have been trying to "Add Cluster" to my Rancher 2.0.8 deployment and continue to be unable to  authenticate to a Packet Project using both existing and new project IDs & my Packet API key.  Any assistance would be appreciated.

**Comment by mmack** [comment]
Same here.

**Comment by displague** [comment]
@mmack could you try running with debugging enabled: https://github.com/packethost/docker-machine-driver-packet#debugging

Please check (and double-check) for any API tokens and Project IDs that may be included in the output, and remove those.  I'm expecting that you will find a 4xx or 5xx API response that will help us identify the problem.

Let us know if you are using a Project API key or a User API key, there are limitations in using a Project API key.

It's also worth noting if your account has access to the facility and plans that are specified here.

Try using the packet cli (https://github.com/packethost/packet-cli#installation) with the same token:
```
$ cat ~/.packet-cli.yaml 
---
token: ...
```

```
$ packet plan get | grep $THE_PLAN_YOU_WANT
$ packet facility get | grep $THE_FACILITY_YOU_WANT
```
Not all images are available in all facilities, so we could be running into a problem there.

**Comment by mmack** [comment]
@displague 
ok i got the error: First i used the project api key and not my user's one. And secondly i configured the node driver's whitelisted domain's wrong. (one need to "lines" in the UI and not just paste "api.packet.net ,tinkerbell.org" into one line.)

Thanks for the help!

**Comment by displague** [comment]
>  And secondly i configured the node driver's whitelisted domain's wrong. (one need to "lines" in the UI and not just paste "api.packet.net ,tinkerbell.org" into one line.)

You are using this in Rancher? You should be able to enable the Packet provider that ships in the Rancher UI to get the correct domains.

I'm curious - how does tinkerbell.org play into your utilization of docker-machine-driver-packet?

**Comment by displague** [comment]
@evectis @mmack I'm going to close this out for staleness. 

@mmack I am interested in your response to my previous question, feel free to respond here.

@evectis If this problem is still affecting you, open an issue on https://github.com/packethost/ui-driver-packet. The solution @mmack offered could be related.  Verify that you are using a User API Key because Project API keys do not have the same features.
