### ISSUE TITLE
Add Drone Cloud CI for docker-machine-driver-packet 

### ISSUE THREAD

**Issue by vielmetti** [packethost/docker-machine-driver-packet#35]
Add a .drone.yml to help do CI for this package - it would be super helpful to check PRs to make sure that they at the minimum pass a build and test check.

**Comment by vielmetti** [comment]
attn @mmlb

**Comment by mmlb** [comment]
ack

**Comment by jasmingacic** [comment]
@amenowanna Should we go ahead with travis or drone here? The timing is perfect.

**Comment by vielmetti** [comment]
@jasmingacic what did you decide?

**Comment by jasmingacic** [comment]
@vielmetti Both are good. I'd suggest maybe using drone since I see it being used in GO and Python SDKs so maybe it is a good idea to have the same CI accross all SDKs.

**Comment by displague** [comment]
Closing as we are now using GitHub workflows for CI tests and releases.
