### ISSUE TITLE
Support a userdata option

### ISSUE THREAD

**Issue by joshwget** [packethost/docker-machine-driver-packet#9]
Similar to `--amazonec2-userdata` and `--digitalocean-userdata`, it would be useful if the Packet driver had a way to upload userdata for launching an instance.

**Comment by crunchywelch** [comment]
good idea, will see if we can get this in the next cycle

**Comment by crunchywelch** [comment]
this is in master now, will push a new release once I'm done with some other debugging. Have fun!

**Comment by joshwget** [comment]
Awesome, thanks @crunchywelch!
